### ISSUE TITLE
Show notification doesn’t work. 

### ISSUE THREAD

**Issue by WilsontheWolf** [itsjafer/StopShortcutsNotifications#1]
This tweak will break the show notification shortcut. Here is a [video](https://media.discordapp.net/attachments/525506616574083072/677799018537025542/video0.mp4) of it in action. The best idea would be to filter if it says running your automation, or something like that.

**Comment by itsjafer** [comment]
Hey could you update to v1.1.0 and see if that fixes this problem?

**Comment by WilsontheWolf** [comment]
Can confirm it works as a normal shortcut and an automation. 👍🏻
